from pathlib import Path
import numpy as np
import pandas as pd
import scipy.io as sio

class SleepScoreMetricsIO:
    """Class to read in .mat files generated by SleepScoreMaster containing sleep score metrics
    including EMG, theta, and slow wave data derived from LFP.

    SleepScoreMaster is found at https://github.com/buzsakilab/buzcode in the 'detectors' folder and is built
    in MATLAB."""
    def __init__(self, basedir):
        self.basedir = Path(basedir)
        self.emg_params = None
    def read_emg(self):
        """Read in pseudo-EMG from SleepScoreMaster"""

        # Get file and check only one present
        emg_files = sorted(self.basedir.glob("*.EMGFromLFP.LFP.mat"))
        assert len(emg_files) == 1, f"1 EMG file expected, f{len(emg_files)} files found"
        emg_file = emg_files[0]

        # Read in file
        emg_dict = sio.loadmat(emg_file, simplify_cells=True)['EMGFromLFP']

        # Make into DataFrame
        emg_df = pd.DataFrame({"timestamps": emg_dict["timestamps"], "pEMG": emg_dict["data"]})

        # Save MetaData - Not working due to pd.DataFrame.attrs being experimental currently
        self.emg_params = {"channels": emg_dict["channels"], "SampleRate": emg_dict["samplingFrequency"],
                           "detectorName": emg_dict["detectorName"]}
        # emg_df.attrs = {"channels": emg_dict["channels"], "SampleRate": emg_dict["samplingFrequency"],
        #                 "detectorName": emg_dict["detectorName"]}

        return emg_df

    def read_metrics(self):
        """Read in sleep score metrics (EMG, theta, slow wave) from SleepScoreMaster"""

        # Get file and check only one present
        metrics_files = sorted(self.basedir.glob("*.SleepScoreMetrics_raw.LFP.mat"))
        assert len(metrics_files) == 1, f"1 metrics file expected, {len(metrics_files)} files found"
        metrics_file = metrics_files[0]

        # Read in file
        metrics_dict = sio.loadmat(metrics_file, simplify_cells=True)['SleepScoreMetrics_raw']

        # Make into DataFrame
        # Subfields: broadbandslowwave_raw, thratio_raw, motiondata_raw, t_clus, badtimes, badtimes_TH, recordingname
        metrics_df = pd.DataFrame({
            "timestamps": metrics_dict["t_clus"],
            "EMG": metrics_dict["motiondata_raw"],
            "theta": metrics_dict["thratio_raw"],
            "slowwave": metrics_dict["broadbandSlowWave_raw"]
        })

        return metrics_df
